config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :order_items, only: [:create, :update, :destroy]
  resource  :cart, only: :show
  get    'signin',  to: 'session#new',     as: 'signin'
  post   'signin',  to: 'session#create'
  delete 'signout', to: 'session#destroy'
  get    'signup',  to: 'users#new',       as: 'signup'
  post   'signup',  to: 'users#create',    as: 'users'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :firstname, :lastname, presence: true

  def full_name
    "#{self.firstname} #{self.lastname}"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :not_signed_user
  before_action :authenticate_admin, if: :signed_in?

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "The author successfully created."
      redirect_to authors_path
    else
      flash.now[:danger] = "The form contains some errors."
      render :new
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      flash[:success] = "The author successfully updated."
      redirect_to authors_path
    else
      flash.now[:danger] = "The form contains some errors."
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:warning] = "The author successfully removed."
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:firstname, :lastname, :biography)
  end
end

app/views/authors/_form.html.haml
- if @author.errors.any?
  %div.errors
    %ul
      - @author.errors.full_messages.each do |error|
        %li= error

.row
  .col-md-offset-3.col-md-6
    = form_for @author do |f|
      .form-group
        = f.label :firstname, 'First Name'
        = f.text_field :firstname, class: 'form-control'
      .form-group
        = f.label :lastname, 'Last Name'
        = f.text_field :lastname, class: 'form-control'
      .form-group
        = f.label :biography
        = f.text_area :biography, class: 'form-control'
      .form-group
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/authors/edit.html.haml
%h1 Edit author

= render 'form'

app/views/authors/index.html.haml
%h1 Authors

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Name
      %th Biography
      %th Options
  %tbody
    - @authors.each do |author|
      %tr
        %th{scope: 'row'}= author.id
        %td= link_to "#{author.firstname} #{author.lastname}", author
        %td= author.biography
        %td
          = link_to 'Edit', edit_author_path(author), class: 'btn btn-success btn-xs'
          = link_to 'Delete', author_path(author), class: 'btn btn-danger btn-xs',
            method: :delete, data: { confirm: 'Are you sure?' }

%p= link_to 'Add new author', new_author_path, class: 'btn btn-primary'

app/views/authors/new.html.haml
%h1 Add new author

= render 'form'