config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :order_items, only: [:create, :update, :destroy]
  resource  :cart, only: :show
  get    'signin',  to: 'session#new',     as: 'signin'
  post   'signin',  to: 'session#create'
  delete 'signout', to: 'session#destroy'
  get    'signup',  to: 'users#new',       as: 'signup'
  post   'signup',  to: 'users#create',    as: 'users'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  has_many :ratings, dependent: :destroy

  validates :title, :price, :stock, presence: true
  validates :title, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, except: [:index, :new, :create]
  before_action :not_signed_user, except: :show
  before_action :authenticate_admin, if: :signed_in?, except: :show

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = "The book successfully added."
      redirect_to @book
    else
      flash[:danger] = "The form contains some errors."
      render :new
    end
  end

  def update
    if @book.update(book_params)
      flash[:success] = "The book successfully updated."
      redirect_to @book
    else
      flash[:danger] = "The form contains some errors."
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:warning] = "The book successfully removed."
    redirect_to books_path
  end

  private

  def load_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :price, :stock,
      :category_id, :author_id)
  end
end

app/views/books/_form.html.haml
- if @book.errors.any?
  %div.errors
    %ul
      - @book.errors.full_messages.each do |error|
        %li= error

.row
  .col-md-offset-3.col-md-6
    = form_for @book do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :author
        = f.collection_select :author_id, Author.all, :id, :full_name,
          { prompt: true }, { class: 'form-control' }
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :category
        = f.collection_select :category_id, Category.all, :id, :title,
          { prompt: true }, { class: 'form-control' }
      .form-group
        = f.label :price
        = f.number_field :price, class: 'form-control'
      .form-group
        = f.label :stock
        = f.number_field :stock, class: 'form-control'
      .form-group
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/books/edit.html.haml
%h1 Edit book

= render 'form'

app/views/books/index.html.haml
%h1 Book Depository

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Title
      %th Price
      %th Stock
      %th Options
  %tbody
    - @books.each do |book|
      %tr
        %th{scope: 'row'}= book.id
        %th= link_to book.title, book
        %th= book.price
        %th= book.stock
        %th
          = link_to 'Edit', edit_book_path(book), class: 'btn btn-success btn-xs'
          = link_to 'Delete', book_path(book), class: 'btn btn-danger btn-xs',
            method: :delete, data: { confirm: 'Are you sure?' }

%p= link_to 'Add new book', new_book_path, class: 'btn btn-primary btn-sm'

app/views/books/new.html.haml
%h1 Add new book

= render 'form'

app/views/books/show.html.haml
%h1= @book.title

- if @book.author.present?
  %p= "Author: #{@book.author.full_name}"
- if @book.category.present?
  %p= "Category: #{@book.category}"
%p= @book.description
%p= "Stock: #{@book.stock}"
%p= "Price: #{number_to_currency(@book.price)}"

= button_to 'Add to Cart', order_items_path(book_id: @book),
  class: 'btn btn-success btn-sm'

- if signed_in? && current_user.is_admin?
  %div
    = link_to 'Edit', edit_book_path(@book)
    = link_to 'Delete', book_path(@book), method: :delete,
      data: { confirm: 'Are you sure?' }