config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :order_items, only: [:create, :update, :destroy]
  resource  :cart, only: :show
  get    'signin',  to: 'session#new',     as: 'signin'
  post   'signin',  to: 'session#create'
  delete 'signout', to: 'session#destroy'
  get    'signup',  to: 'users#new',       as: 'signup'
  post   'signup',  to: 'users#create',    as: 'users'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  def to_s
    self.title
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, except: [:index, :new, :create]
  before_action :not_signed_user, except: :show
  before_action :authenticate_admin, if: :signed_in?, except: :show

  def index
    @categories = Category.all
  end

  def show
    @books = @category.books
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "The category successfully created."
      redirect_to categories_path
    else
      flash[:danger] = "The form contains some errors."
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "The category successfully updated."
      redirect_to categories_path
    else
      flash[:danger] = "The form contains some errors."
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:warning] = "The category successfully removed."
    redirect_to categories_path
  end

  private

  def load_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/views/categories/_form.html.haml
- if @category.errors.any?
  %div.errors
    %ul
      - @category.errors.full_messages.each do |error|
        %li= error

.row
  .col-md-offset-3.col-md-6
    = form_for @category do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/categories/edit.html.haml
%h1 Edit category

= render 'form'

app/views/categories/index.html.haml
%h1 Categories

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Title
      %th Options
  %tbody
    - @categories.each do |category|
      %tr
        %th{scope: 'row'}= category.id
        %td= link_to category.title, category
        %td
          = link_to 'Edit', edit_category_path(category), class: 'btn btn-success btn-xs'
          = link_to 'Delete', category_path(category), class: 'btn btn-danger btn-xs',
            method: :delete, data: { confirm: 'Are you sure?' }

%p= link_to "Add new category", new_category_path, class: "btn btn-primary btn-sm"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

app/views/categories/show.html.haml
%h1= @category.title

%ul.list-unstyled
  - @books.each do |book|
    %li.row.entry
      %h3= link_to book.title, book_path(book)
      %div= book.description
      %div.price_line
        %span.price= number_to_currency(book.price)
        = button_to 'Add to Cart', order_items_path(book_id: book),
          class: 'btn btn-success btn-sm'