config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :order_items, only: [:create, :update, :destroy]
  resource  :cart, only: :show
  get    'signin',  to: 'session#new',     as: 'signin'
  post   'signin',  to: 'session#create'
  delete 'signout', to: 'session#destroy'
  get    'signup',  to: 'users#new',       as: 'signup'
  post   'signup',  to: 'users#create',    as: 'users'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Book Depository
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .container
        .navbar-header
          = link_to 'Book Depository', root_path, class: 'navbar-brand logo'
        %nav
          %ul.nav.navbar-nav.navbar-right
            - if signed_in?
              %li= link_to 'Cart', cart_path
              %li= link_to 'Sign out', signout_path, method: :delete
            - else
              %li= link_to 'Sign in', signin_path
              %li= link_to 'Sign up', signup_path
    .container
      .row
        .col-md-3
          .list-group
            - Category.order(:title).each do |category|
              - act = params[:id] == category.id.to_s ? ' active' : nil
              = link_to category.title, category, class: "list-group-item#{act}"
        .col-md-9
          - flash.each do |name, msg|
            = content_tag :div, msg, class: "alert alert-#{name}"
          = yield